site_name: AI Yome Project
nav:
  - Home: index.md
  - 計画＆サーベイ:
    - surveys/language_understanding.md
    - surveys/motion_generation.md
    - surveys/spatial_perception.md
    - surveys/3d_engine.md
    - surveys/development_env.md
    - surveys/physics.md
  - 基礎知識:
    - 開発環境:
      - Streamlit:
        - knowledges/dev_envs/streamlit_for_development.md
  - プロジェクト:
    - VSLAM (Virtual Sex Life Augmenting Mechanism):
      - projects/vslam/roadmap.md
      - projects/vslam/3d_model_and_animation.md
      - projects/vslam/waist_motion_detection.md
    - Interactive Character:
      - projects/interactive_character/fuwamiku.md
      - projects/interactive_character/sense_map.md
  - 開発者プロフィール: 
    - developer_profile.md
theme:
  name: material
  features:
    - tabs
  palette:
    primary: light blue
    accent: light blue
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/xiong-jie-y
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_xiongjie_
  manifest: manifest.webmanifest
google_analytics:
  - UA-55455142-8
  - auto
markdown_extensions:
  - mdx_truly_sane_lists:
      nested_indent: 2
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML